services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: node dist/index.js
    restart: unless-stopped

  worker:
    build: .
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: node dist/worker.js
    restart: unless-stopped
    depends_on:
      - api
