export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SCHEDULE_ALREADY_RUNNING: 'SCHEDULE_ALREADY_RUNNING',
  SCHEDULE_ALREADY_TERMINAL: 'SCHEDULE_ALREADY_TERMINAL',
  SCHEDULE_NOT_CANCELLABLE: 'SCHEDULE_NOT_CANCELLABLE',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  TASK_TIMEOUT: 'TASK_TIMEOUT',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  FILE_PARSE_ERROR: 'FILE_PARSE_ERROR',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  UNSUPPORTED_TASK_TYPE: 'UNSUPPORTED_TASK_TYPE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
